import * as vscode from 'vscode';
import { AIController } from '../controllers/AIController';

export class FixActionProvider implements vscode.CodeActionProvider {
    constructor(context: vscode.ExtensionContext) {
    }

    provideCodeActions(document: vscode.TextDocument, range: vscode.Range | vscode.Selection, context: vscode.CodeActionContext, token: vscode.CancellationToken): vscode.ProviderResult<(vscode.Command | vscode.CodeAction)[]> {
        const actions: vscode.CodeAction[] = [];

        // Look for diagnostics generated by Fiction Linter
        for (const diagnostic of context.diagnostics) {
            if (diagnostic.source === 'Fiction Linter') {
                const fixAction = this.createFixAction(document, diagnostic);
                actions.push(fixAction);
            }
        }

        return actions;
    }

    private createFixAction(document: vscode.TextDocument, diagnostic: vscode.Diagnostic): vscode.CodeAction {
        const action = new vscode.CodeAction(`Fix with AI: ${diagnostic.message}`, vscode.CodeActionKind.QuickFix);

        // We use a command here because the AI generation is async and takes time.
        // A direct WorkspaceEdit in the CodeAction is better for synchronous/instant edits.
        // For AI, we trigger a command that shows a progress indicator.
        action.command = {
            command: 'fiction-linter.fixWithAI',
            title: 'Fix with AI',
            arguments: [document, diagnostic.range, diagnostic.message]
        };

        action.diagnostics = [diagnostic];
        action.isPreferred = true;
        return action;
    }
}
